### ISSUE TITLE
Image styles with cropping

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat10-profile#191]
Related to CuBoulder/tiamat-theme#1125 , I think it's because these image styles aren't using the focal point when the image is cropped.

All image styles that do any sort of cropping should include the focal point scale & crop in the image style processing, rather than providing separate image styles to choose from.

Image styles that only scale the image, but retain the original aspect ratio and do not crop the image do not need to include this in the processing.

**Comment by kevincrafts** [comment]
> There is supposed to be a resave enities function coming in drupal 11.1ish.

You shouldn't need to resave the entity when making a change like this, it's just that you want to allow Drupal to recreate the image derivatives since they were changed. It looks like there's a drush command you can run that you can call specific image styles to be cleared and they will be automatically rebuild as needed. 

https://www.drush.org/13.x/commands/image_flush/

**Comment by jnicholCU** [comment]
@kevincrafts it looks like these should all be working fine. I did some testing on Nicole's sandbox and I'm not having any issues with blocks vs embeds not updating properly with new focal information. 
I did update styles that cropped but weren't using the focal crop so now all of those should be using it. 

The only place I know won't update are section background pictures because the focal data gets saved as serialized php upon form submission. However this is what is getting worked on to hopefully have working different in `D11.1`
